alias: null
batch_size: 32
context_size: 10
decoder_hidden_size: 200
decoder_layers: 2
dilations:
- 1
- 2
- 4
- 8
- 16
drop_last_loader: false
early_stop_patience_steps: -1
encoder_activation: ReLU
encoder_hidden_size: 200
futr_exog_list:
- "\uC77C\uC218"
- "\uC8FC\uB9D0\uC218"
- "\uC8FC\uC911\uC218"
- "\uACF5\uD734\uC77C\uC218"
- "\uBA85\uC808\uC218"
- stringency_index
- deaths
- international_movement_restrictions
- people_vaccinated
- people_fully_vaccinated
- containment_health_index
- confirmed
- government_response_index
h: 33
hist_exog_list:
- "\uACF5\uAE09\uCC28\uB7C9\uC218"
- "\uACF5\uAE09\uC88C\uC11D\uD569\uACC4\uC218"
- "\uC2B9\uCC28\uC218\uC785\uAE08\uC561"
- "\uC2B9\uCC28\uC5F0\uC778\uAC70\uB9AC"
- "\uC88C\uC11D\uAC70\uB9AC"
- "1\uC778\uB2F9\uC218\uC785\uC728"
- "\uACF5\uAE09\uB300\uBE44\uC2B9\uCC28\uC728"
- "\uC6B4\uD589\uB300\uBE44\uACE0\uAC1D\uC774\uB3D9"
- "\uAD00\uAD11"
- "\uC77C\uBC18"
- "\uC77C\uBC18/\uAD00\uAD11"
- "\uB300\uC218\uC1A1"
- "\uC784\uC2DC"
- "\uD655\uC815"
- "\uC2DC\uBC1C\uC5ED"
- "\uC885\uCC29\uC5ED"
- "\uC2DC\uBC1C\uC885\uCC29\uC5ED"
- "\uC5F4\uCC28\uC6B4\uD589\uD69F\uC218"
inference_input_size: -1
input_size: 66
kernel_size: 2
learning_rate: 0.001
loss: !!python/object:neuralforecast.losses.pytorch.MQLoss
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - - - quantiles
      - !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYDQAAADIzNjU3NzI5NzY4NDhxAlgDAAAAY3B1cQNLBU50cQRRLoACXXEAWA0AAAAyMzY1
              NzcyOTc2ODQ4cQFhLgUAAAAAAAAAAAAAPwAAAD4AAIA+AABAPwAAYD8=
          - 0
          - !!python/tuple
            - 5
          - !!python/tuple
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - false
        - !!python/object/apply:collections.OrderedDict
          - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  horizon_weight: null
  is_distribution_output: false
  output_names:
  - -median
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGwAAABvAAAALQAAADcAAAA1AAAA
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGwAAABvAAAALQAAADUAAAAwAAAA
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGgAAABpAAAALQAAADUAAAAwAAAA
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGgAAABpAAAALQAAADcAAAA1AAAA
  outputsize_multiplier: 5
  training: true
max_steps: 1000
num_lr_decays: -1
num_workers_loader: 0
optimizer: null
optimizer_kwargs: null
random_seed: 1
scaler_type: robust
stat_exog_list: null
val_check_steps: 100
valid_batch_size: null
valid_loss: null
